package compiler;

import java.util.List;

/**
 * Walks the AST and emits valid Python 3 source code.
 * Python is chosen as target because its indentation-based
 * syntax maps cleanly from our block structure.
 */
public class CodeGenerator {

    private final StringBuilder sb     = new StringBuilder();
    private       int           indent = 0;

    private static final String INDENT_UNIT = "    "; // 4 spaces

    // ── Entry point ───────────────────────────────────────────

    public String generate(ProgramNode program) {
        emitLine("# Generated by অক্ষর Compiler");
        emitLine("# Do not edit this file manually");
        emitLine("");
        for (ASTNode stmt : program.statements) {
            genStatement(stmt);
        }
        return sb.toString();
    }

    // ── Statements ────────────────────────────────────────────

    private void genStatement(ASTNode node) {
        if (node == null) return;

        if      (node instanceof VarDeclNode)  genVarDecl((VarDeclNode) node);
        else if (node instanceof AssignNode)   genAssign((AssignNode) node);
        else if (node instanceof IfNode)       genIf((IfNode) node);
        else if (node instanceof WhileNode)    genWhile((WhileNode) node);
        else if (node instanceof PrintNode)    genPrint((PrintNode) node);
    }

    private void genVarDecl(VarDeclNode node) {
        String safeName = sanitize(node.name);
        if (node.initializer != null) {
            emitLine(safeName + " = " + genExpr(node.initializer));
        } else {
            // default values
            if ("দশমিক".equals(node.type)) {
                emitLine(safeName + " = 0.0");
            } else {
                emitLine(safeName + " = 0");
            }
        }
    }

    private void genAssign(AssignNode node) {
        emitLine(sanitize(node.name) + " = " + genExpr(node.value));
    }

    private void genIf(IfNode node) {
        emitLine("if " + genExpr(node.condition) + ":");
        indent++;
        if (node.thenBranch.isEmpty()) {
            emitLine("pass");
        } else {
            for (ASTNode s : node.thenBranch) genStatement(s);
        }
        indent--;

        if (node.elseBranch != null) {
            emitLine("else:");
            indent++;
            if (node.elseBranch.isEmpty()) {
                emitLine("pass");
            } else {
                for (ASTNode s : node.elseBranch) genStatement(s);
            }
            indent--;
        }
    }

    private void genWhile(WhileNode node) {
        emitLine("while " + genExpr(node.condition) + ":");
        indent++;
        if (node.body.isEmpty()) {
            emitLine("pass");
        } else {
            for (ASTNode s : node.body) genStatement(s);
        }
        indent--;
    }

    private void genPrint(PrintNode node) {
        emitLine("print(" + genExpr(node.expression) + ")");
    }

    // ── Expressions → returns Python expression string ────────

    private String genExpr(ASTNode node) {
        if (node instanceof NumberNode)   return String.valueOf(((NumberNode) node).value);
        if (node instanceof FloatNode)    return String.valueOf(((FloatNode) node).value);
        if (node instanceof StringNode)   return pythonStr(((StringNode) node).value);
        if (node instanceof BoolNode)     return ((BoolNode) node).value ? "True" : "False";
        if (node instanceof IdentifierNode) return sanitize(((IdentifierNode) node).name);

        if (node instanceof UnaryOpNode) {
            UnaryOpNode u = (UnaryOpNode) node;
            if ("!".equals(u.op)) return "(not " + genExpr(u.operand) + ")";
            return "(" + u.op + genExpr(u.operand) + ")";
        }

        if (node instanceof BinaryOpNode) {
            BinaryOpNode b = (BinaryOpNode) node;
            String left  = genExpr(b.left);
            String right = genExpr(b.right);
            String op    = b.op;
            // map && / || to Python
            if ("&&".equals(op)) op = "and";
            if ("||".equals(op)) op = "or";
            return "(" + left + " " + op + " " + right + ")";
        }

        return "None";
    }

    // ── Helpers ───────────────────────────────────────────────

    /**
     * Convert a Bengali identifier to a valid Python identifier.
     * Python 3 supports Unicode identifiers natively, so Bengali
     * variable names like 'ক' are legal Python identifiers already.
     * We just need to make sure no keyword clash occurs.
     */
    private String sanitize(String name) {
        // Python keywords that might clash (unlikely but safe)
        switch (name) {
            case "True": case "False": case "None":
            case "and": case "or": case "not":
            case "if": case "else": case "while":
            case "for": case "in": case "def":
            case "class": case "return": case "print":
                return "_" + name;
            default:
                return name;
        }
    }

    private String pythonStr(String s) {
        // Escape backslashes and double-quotes
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\t", "\\t") + "\"";
    }

    private void emitLine(String line) {
        for (int i = 0; i < indent; i++) sb.append(INDENT_UNIT);
        sb.append(line).append("\n");
    }
}
