# Generated by অক্ষর Compiler
# Do not edit this file manually

ক = 10
খ = 5
গ = 3.14
ফলাফল = 0
ফলাফল = (ক + খ)
print("যোগফল:")
print(ফলাফল)
ফলাফল = (ক - খ)
print("বিয়োগফল:")
print(ফলাফল)
ফলাফল = (ক * খ)
print("গুণফল:")
print(ফলাফল)
ফলাফল = (ক / খ)
print("ভাগফল:")
print(ফলাফল)
ফলাফল = (ক % খ)
print("ভাগশেষ:")
print(ফলাফল)
print("── শর্ত পরীক্ষা ──")
if (ক > খ):
    print("ক বড়")
else:
    print("খ বড় বা সমান")
if (ক == 10):
    if (খ == 5):
        print("ক দশ এবং খ পাঁচ")
    else:
        print("ক দশ কিন্তু খ পাঁচ নয়")
print("── গণনা ১ থেকে ৫ ──")
গণনা = 1
while (গণনা <= 5):
    print(গণনা)
    গণনা = (গণনা + 1)
print("পাই এর মান:")
print(গ)
print("প্রোগ্রাম শেষ হয়েছে!")
